# Generated by Django 4.2 on 2026-04-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('contact_email', models.CharField(max_length=50)),
                ('contact_phone', models.CharField(max_length=20)),
                ('head_officer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('grievance', models.CharField(max_length=40)),
                ('document_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen', models.CharField(max_length=40)),
                ('grievance', models.CharField(max_length=40)),
                ('rating', models.CharField(max_length=10)),
                ('comments', models.CharField(max_length=200)),
                ('feedback_date', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('photo', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('submission_date', models.CharField(max_length=25)),
                ('priority', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='grievanceassignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grievance', models.CharField(max_length=40)),
                ('assigned_officer', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=40)),
                ('assigned_date', models.CharField(max_length=25)),
                ('expected_resolution_date', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='grievancecategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('priority_level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='grievanceupdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grievance', models.CharField(max_length=40)),
                ('officer', models.CharField(max_length=40)),
                ('update_date', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=300)),
                ('photo', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='infrastructureasset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=40)),
                ('installation_date', models.CharField(max_length=25)),
                ('last_maintenance_date', models.CharField(max_length=25)),
                ('condition_status', models.CharField(max_length=20)),
                ('photo', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='infrastructuremonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=40)),
                ('monitored_by', models.CharField(max_length=40)),
                ('inspection_date', models.CharField(max_length=25)),
                ('condition_report', models.CharField(max_length=300)),
                ('defects_found', models.CharField(max_length=200)),
                ('photo', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('action_taken', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=300)),
                ('notification_date', models.CharField(max_length=25)),
                ('is_read', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='userlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='userregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
    ]
