# Generated by Django 4.2 on 2026-07-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='role',
        ),
    ]
