# Generated by Django 4.2 on 2026-07-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_remove_userregistration_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='contact',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='email',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
