# Generated by Django 4.2 on 2026-08-07 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_alter_userregistration_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_read',
            new_name='priority',
        ),
    ]
