# Generated by Django 4.2 on 2026-08-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_rename_is_read_notification_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='grievance_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
