# Generated by Django 4.2 on 2026-08-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_grievance_grievance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='grievance_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
